title: Jekyll-Store
description: 'A lightweight, backend-free ecommerce solution.'

# Jekyll-Store Engine
defaultAddress:
  country: GB
payment:
  tokenizer: Paymill
  currency: GBP
  hook: 'https://jekyll-store-microservice.herokuapp.com/purchase'

# Jekll-Store Front
image_prefix: 'http://res.cloudinary.com/jekyll-store/'
paymillPublicKey: 323027826220f6ed944b96a1a47e35a0

# http://openexchangerates.github.io/accounting.js/#documentation
accounting:
  symbol : '£'
  format: '%s%v'
  decimal : '.'
  thousand: ','
  precision : 2

# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  ignore:
    - _includes
    - _layouts
    - assets
    - json
    - pages
    - .gitignore
    - _config.yml
    - CNAME
    - Gemfile
    - README.md
  metadata:
    _products:
      - name: name
        field:
          element: text
          label: Name
          help: Must be unique
      - name: price
        field:
          element: number
          label: 'Price (£)'
      - name: weight
        field:
          element: number
          label: 'Weight (kg)'
      - name: designer
        field:
          element: text
          label: Designer
      - name: type
        field:
          element: select
          label: Type
          options:
            - value: Wood
            - value: Metal
            - value: Metallic
      - name: condition
        field:
          element: select
          label: Condition
          options:
            - value: Mint
            - value: Worn
            - value: Rough
      - name: image1
        field:
          element: text
          label: Image 1
      - name: image2
        field:
          element: text
          label: Image 2

# http://jekyllrb.com/docs/configuration/
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  products:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: 'products'
    values:
      layout: 'product'
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'CNAME']